# Global settings
global:
  database:
    user: user
    password: password
    dbName: scac
  jwtSecret: secret
  apiGatewayPort: 8000
  clientPort: 3000

# Postgres settings
database:
  image: postgres:17.2-bookworm
  servicePort: 5432
  volumeSize: 10Gi

# Redis settings
redis:
  image: redis:7.4.1-bookworm
  servicePort: 6379

# Services settings
services:
  common:
    imagePullPolicy: Always
    loggingLevel: debug
    replicas: 3
  actionsService:
    image: ghcr.io/tectek-solutions/scac:actions-service-latest
  apisService:
    image: ghcr.io/tectek-solutions/scac:apis-service-latest
  authenticationsService:
    image: ghcr.io/tectek-solutions/scac:authentications-service-latest
  reactionsService:
    image: ghcr.io/tectek-solutions/scac:reactions-service-latest
  triggerService:
    image: ghcr.io/tectek-solutions/scac:trigger-service-latest
  userTokensService:
    image: ghcr.io/tectek-solutions/scac:user-tokens-service-latest
  usersService:
    image: ghcr.io/tectek-solutions/scac:users-service-latest
  workflowsService:
    image: ghcr.io/tectek-solutions/scac:workflows-service-latest
  apiGateway:
    image: ghcr.io/tectek-solutions/scac:api-gateway-latest
  client:
    image: ghcr.io/tectek-solutions/scac:client-latest
