networks:
  internal:
    driver: bridge

volumes:
  database-data:
    driver: local

services:
  database:
    image: postgres:17.2-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "log_statement=all"]
    expose:
      - "5432"
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - database-data:/var/lib/postgresql/data

  cache:
    image: redis:7.4.1-bookworm
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "6379"
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  migration:
    build:
      context: .
      dockerfile: ./shared/database/Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy

  actions-service:
    build:
      context: .
      dockerfile: ./services/actions-service/Dockerfile
    expose:
      - "8000"
    environment:
      RUST_LOG: info
      BINDING_ADDRESS: 0.0.0.0
      BINDING_PORT: 8000
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      REDIS_URL: redis://cache:6379
      JWT_SECRET: ${JWT_SECRET}
      API_URL: http://localhost:8000
    networks:
      - internal
    depends_on:
      - migration
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  apis-service:
    build:
      context: .
      dockerfile: ./services/apis-service/Dockerfile
    expose:
      - "8000"
    environment:
      RUST_LOG: info
      BINDING_ADDRESS: 0.0.0.0
      BINDING_PORT: 8000
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      REDIS_URL: redis://cache:6379
      JWT_SECRET: ${JWT_SECRET}
      API_URL: http://localhost:8000
    networks:
      - internal
    depends_on:
      - migration
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  authentications-service:
    build:
      context: .
      dockerfile: ./services/authentications-service/Dockerfile
    expose:
      - "8000"
    environment:
      RUST_LOG: info
      BINDING_ADDRESS: 0.0.0.0
      BINDING_PORT: 8000
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      REDIS_URL: redis://cache:6379
      JWT_SECRET: ${JWT_SECRET}
      API_URL: http://localhost:8000
    networks:
      - internal
    depends_on:
      - migration
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  reactions-service:
    build:
      context: .
      dockerfile: ./services/reactions-service/Dockerfile
    expose:
      - "8000"
    environment:
      RUST_LOG: info
      BINDING_ADDRESS: 0.0.0.0
      BINDING_PORT: 8000
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      REDIS_URL: redis://cache:6379
      JWT_SECRET: ${JWT_SECRET}
      API_URL: http://localhost:8000
    networks:
      - internal
    depends_on:
      - migration
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  trigger-service:
    build:
      context: .
      dockerfile: ./services/trigger-service/Dockerfile
    expose:
      - "8000"
    environment:
      RUST_LOG: info
      BINDING_ADDRESS: 0.0.0.0
      BINDING_PORT: 8000
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      REDIS_URL: redis://cache:6379
      JWT_SECRET: ${JWT_SECRET}
      API_URL: http://localhost:8000
    networks:
      - internal
    depends_on:
      - migration
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  user-tokens-service:
    build:
      context: .
      dockerfile: ./services/user-tokens-service/Dockerfile
    expose:
      - "8000"
    environment:
      RUST_LOG: info
      BINDING_ADDRESS: 0.0.0.0
      BINDING_PORT: 8000
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      REDIS_URL: redis://cache:6379
      JWT_SECRET: ${JWT_SECRET}
      API_URL: http://localhost:8000
      CLIENT_URL: http://localhost:3000
    networks:
      - internal
    depends_on:
      - migration
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  users-service:
    build:
      context: .
      dockerfile: ./services/users-service/Dockerfile
    expose:
      - "8000"
    environment:
      RUST_LOG: info
      BINDING_ADDRESS: 0.0.0.0
      BINDING_PORT: 8000
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      REDIS_URL: redis://cache:6379
      JWT_SECRET: ${JWT_SECRET}
      API_URL: http://localhost:8000
    networks:
      - internal
    ports:
      - "9000:8000"
    depends_on:
      - migration
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  workflows-service:
    build:
      context: .
      dockerfile: ./services/workflows-service/Dockerfile
    expose:
      - "8000"
    environment:
      RUST_LOG: info
      BINDING_ADDRESS: 0.0.0.0
      BINDING_PORT: 8000
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      REDIS_URL: redis://cache:6379
      JWT_SECRET: ${JWT_SECRET}
      API_URL: http://localhost:8000
    networks:
      - internal
    depends_on:
      - migration
      - cache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      RUST_LOG: info
      BINDING_ADDRESS: 0.0.0.0
      BINDING_PORT: 8000
      ACTIONS_SERVICE_ADDRESS: actions-service
      ACTIONS_SERVICE_PORT: 8000
      APIS_SERVICE_ADDRESS: apis-service
      APIS_SERVICE_PORT: 8000
      AUTHENTICATIONS_SERVICE_ADDRESS: authentications-service
      AUTHENTICATIONS_SERVICE_PORT: 8000
      REACTIONS_SERVICE_ADDRESS: reactions-service
      REACTIONS_SERVICE_PORT: 8000
      TRIGGER_SERVICE_ADDRESS: trigger-service
      TRIGGER_SERVICE_PORT: 8000
      USER_TOKENS_SERVICE_ADDRESS: user-tokens-service
      USER_TOKENS_SERVICE_PORT: 8000
      USERS_SERVICE_ADDRESS: users-service
      USERS_SERVICE_PORT: 8000
      WORKFLOWS_SERVICE_ADDRESS: workflows-service
      WORKFLOWS_SERVICE_PORT: 8000
    networks:
      - internal
    depends_on:
      - actions-service
      - apis-service
      - authentications-service
      - reactions-service
      - trigger-service
      - user-tokens-service
      - users-service
      - workflows-service
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URL: http://localhost:8000
    networks:
      - internal
    depends_on:
      - api-gateway
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

