[package]
name = "jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
jwt = "0.16.0"
regex = "1.11.1"
hmac = "0.12.1"
sha2 = "0.10.8"
chrono = { version = "0.4.38", features = ["serde"] }
cache = { path = "../cache" }
actix-web = "4.9.0"
redis = "0.20.2"