[package]
name = "users-service"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "users-service"
path = "src/main.rs"

[dependencies]
diesel = { version = "2.0.0", features = ["postgres", "chrono"] }
database = { path = "../../shared/database" }
