apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  postgres-password: {{ .Values.global.database.password | b64enc }}
  jwt-secret: {{ .Values.global.jwtSecret | b64enc }}
