apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.name }}"
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    targetPort: 8000
  selector:
    app: {{ .Chart.Name }}
    service: {{ .Values.name }}
