name: Deploy Argo CD

on:
  push:
    branches:
      - main
      - 43-fix-the-github-actions-for-deploy-helm-charts

jobs:
  call-deploy-template:
    uses: ./.github/workflows/deploy-helm-template.yml
    secrets: inherit
    with:
      release-name: "argo-cd"
      namespace: "argo-cd"
      chart-path: "./deployments/argo-cd"
      values-file: "./deployments/argo-cd/values.yaml"
    