name: Deploy Argo CD

on:
  push:
    branches:
      - main
      - 43-fix-the-github-actions-for-deploy-helm-charts

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo TEST secret
        run: echo ${{ secrets.TEST }}

  call-deploy-template:
    uses: ./.github/workflows/deploy-helm-template.yml
    with:
      release-name: "argo-cd"
      namespace: "argo-cd"
      chart-path: "./deployments/argo-cd"
      values-file: "./deployments/argo-cd/values.yaml"
