name: Deploy Helm Chart

on:
  workflow_call:
    inputs:
      chart-path:
        description: Path to the Helm chart
        required: true
        type: string
      release-name:
        description: Name of the Helm release
        required: true
        type: string
      namespace:
        description: Namespace to deploy the Helm release
        required: true
        type: string
      values-file:
        description: Path to the values file (optional)
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set Kubeconfig
        run: doctl kubernetes cluster kubeconfig save "${{ secrets.KUBERNETES_CLUSTER_ID }}"

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.2

      - name: Helm Dependency Update
        run: helm dependency update "${{ inputs.chart-path }}"

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install "${{ inputs.release-name }}" "${{ inputs.chart-path }}" \
            --namespace "${{ inputs.namespace }}" \
            --create-namespace \
            $(if [ -n "${{ inputs.values-file }}" ]; then echo "--values=${{ inputs.values-file }}"; fi)
