name: Deploy Helm Chart

on:
  workflow_call:
    inputs:
      release-name:
        description: "The name of the Helm release"
        required: true
        type: string
      namespace:
        description: "The Kubernetes namespace to deploy to"
        required: true
        type: string
      chart-path:
        description: "Path to the Helm chart"
        required: false
        default: "./"
        type: string
      values-file:
        description: "Path to the values.yaml file"
        required: false
        default: "./values.yaml"
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set Kubeconfig
        run: doctl kubernetes cluster kubeconfig save "${{ secrets.KUBERNETES_CLUSTER_ID }}"
    
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.2

      - name: Helm Dependency Update
        run: |
          helm dependency update "${{ inputs.chart-path }}"

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ${{ inputs.release-name }} "${{ inputs.chart-path }}" \
            --namespace ${{ inputs.namespace }} \
            --create-namespace \
            --values "${{ inputs.values-file }}"
