name: Deploy Kube Prometheus Stack

on:
  push:
    branches:
      - main
      - 43-fix-the-github-actions-for-deploy-helm-charts

jobs:
  call-deploy-template:
    uses: ./.github/workflows/deploy-helm-template.yml
    secrets: inherit
    with:
      release-name: "kube-prometheus-stack"
      namespace: "kube-prometheus-stack"
      chart-path: "./deployments/kube-prometheus-stack"
      values-file: "./deployments/kube-prometheus-stack/values.yaml"
