name: Deploy Kube Prometheus Stack

on:
  push:
    branches:
      - main
      - 43-fix-the-github-actions-for-deploy-helm-charts

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo TEST secret
        run: |
          echo ${{ secrets.TEST }}
          echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          echo ${{ secrets.KUBERNETES_CLUSTER_ID }}

  call-deploy-template:
    uses: ./.github/workflows/deploy-helm-template.yml
    with:
      release-name: "kube-prometheus-stack"
      namespace: "kube-prometheus-stack"
      chart-path: "./deployments/kube-prometheus-stack"
      values-file: "./deployments/kube-prometheus-stack/values.yaml"
