name: Docker - Users Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-template:
    uses: ./.github/workflows/docker-image-template.yml
    with:
      dockerfile: ./services/users-service/Dockerfile
      image_name: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:users-service-latest
      context: ./services/users-service/
      push_on_main: true
