name: Docker - Workflow Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build Docker image
        run: |
          docker buildx build \
            --file ./services/workflow-service/Dockerfile \
            --tag ${{ github.event.repository.name }}:workflow-service-latest \
            ./services/workflow-service/

      - name: If not the branch main, exit
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "Not on the main branch, skipping push."

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker push workflow-service:latest

      - name: Login to GHCR
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:workflow-service-latest