name: Docker - Workflow Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-template:
    uses: ./.github/workflows/docker-image-template.yml
    with:
      dockerfile: ./services/workflow-service/Dockerfile
      image_name: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:workflow-service-latest
      context: ./services/workflow-service/
      push_on_main: true
